name: release

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libcurl4-openssl-dev
      - name: Build project # This would actually build your project, using zip for an example artifact
        run: |
          ./bootstrap
          ./configure --prefix=./bin
          make
          make install
          ls -1
