name: release

on:
  push:
    branches:
      - '*'
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install libcurl4-openssl-dev
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libcurl4-openssl-dev
      - name: Build project # This would actually build your project, using zip for an example artifact
        run: |
          ./bootstrap
          ./configure --prefix=${GITHUB_WORKSPACE}/bin
          make
          make install
